name: Build and Tests

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      # generate the docs so the test to serve documentation passes
      - run: npm run docs
      - run: npm test

      - name: Upload coverage data to Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@v2
    
  circular-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install -g madge
      - run: madge src/App.ts -c

  generate-and-deploy-docs:
    needs: [build-and-tests, circular-dependencies]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate API documentation
        run: npx apidoc -i src/routes/ -o doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
